"""baseline schema

Revision ID: 0001
Revises: 
Create Date: 2026-08-11 01:44:28.763501
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision: str = '0001'
down_revision: str | None = None
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.String(), nullable=False),
    sa.Column('finished_at', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('pipeline_version', sa.String(), nullable=False),
    sa.Column('input_dir', sa.String(), nullable=False),
    sa.Column('images_total', sa.Integer(), nullable=False),
    sa.Column('images_processed', sa.Integer(), nullable=False),
    sa.Column('images_cached', sa.Integer(), nullable=False),
    sa.Column('config_json', sa.Text(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artwork_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('version_label', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('sha256', sa.String(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('approved_at', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artwork_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artwork_versions_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_artwork_versions_sha256'), ['sha256'], unique=False)
        batch_op.create_index('ix_version_product_label', ['product_id', 'version_label'], unique=False)

    op.create_table('scraped_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('source_path', sa.String(), nullable=False),
    sa.Column('sha256', sa.String(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scraped_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scraped_images_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scraped_images_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scraped_images_sha256'), ['sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_scraped_images_source_path'), ['source_path'], unique=False)

    op.create_table('acknowledgements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('region_signature', sa.String(), nullable=False),
    sa.Column('reference_version_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['reference_version_id'], ['artwork_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('acknowledgements', schema=None) as batch_op:
        batch_op.create_index('ix_ack_lookup', ['region_signature', 'reference_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_acknowledgements_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_acknowledgements_reference_version_id'), ['reference_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_acknowledgements_region_signature'), ['region_signature'], unique=False)

    op.create_table('discriminating_regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('from_version_id', sa.Integer(), nullable=False),
    sa.Column('to_version_id', sa.Integer(), nullable=False),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('w', sa.Integer(), nullable=False),
    sa.Column('h', sa.Integer(), nullable=False),
    sa.Column('area_fraction', sa.Float(), nullable=False),
    sa.Column('field_key', sa.String(), nullable=True),
    sa.Column('old_value', sa.String(), nullable=True),
    sa.Column('new_value', sa.String(), nullable=True),
    sa.Column('edit_type', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['from_version_id'], ['artwork_versions.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['to_version_id'], ['artwork_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('discriminating_regions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discriminating_regions_from_version_id'), ['from_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_discriminating_regions_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_discriminating_regions_to_version_id'), ['to_version_id'], unique=False)

    op.create_table('findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('scraped_image_id', sa.Integer(), nullable=False),
    sa.Column('verdict', sa.String(), nullable=False),
    sa.Column('matched_version_id', sa.Integer(), nullable=True),
    sa.Column('current_version_id', sa.Integer(), nullable=True),
    sa.Column('match_method', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('diff_map_path', sa.String(), nullable=True),
    sa.Column('regions_json', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['current_version_id'], ['artwork_versions.id'], ),
    sa.ForeignKeyConstraint(['matched_version_id'], ['artwork_versions.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['scraped_image_id'], ['scraped_images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_findings_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_verdict'), ['verdict'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_findings_verdict'))
        batch_op.drop_index(batch_op.f('ix_findings_severity'))
        batch_op.drop_index(batch_op.f('ix_findings_run_id'))
        batch_op.drop_index(batch_op.f('ix_findings_product_id'))

    op.drop_table('findings')
    with op.batch_alter_table('discriminating_regions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discriminating_regions_to_version_id'))
        batch_op.drop_index(batch_op.f('ix_discriminating_regions_product_id'))
        batch_op.drop_index(batch_op.f('ix_discriminating_regions_from_version_id'))

    op.drop_table('discriminating_regions')
    with op.batch_alter_table('acknowledgements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_acknowledgements_region_signature'))
        batch_op.drop_index(batch_op.f('ix_acknowledgements_reference_version_id'))
        batch_op.drop_index(batch_op.f('ix_acknowledgements_product_id'))
        batch_op.drop_index('ix_ack_lookup')

    op.drop_table('acknowledgements')
    with op.batch_alter_table('scraped_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scraped_images_source_path'))
        batch_op.drop_index(batch_op.f('ix_scraped_images_sha256'))
        batch_op.drop_index(batch_op.f('ix_scraped_images_run_id'))
        batch_op.drop_index(batch_op.f('ix_scraped_images_product_id'))

    op.drop_table('scraped_images')
    with op.batch_alter_table('artwork_versions', schema=None) as batch_op:
        batch_op.drop_index('ix_version_product_label')
        batch_op.drop_index(batch_op.f('ix_artwork_versions_sha256'))
        batch_op.drop_index(batch_op.f('ix_artwork_versions_product_id'))

    op.drop_table('artwork_versions')
    op.drop_table('runs')
    op.drop_table('products')
    # ### end Alembic commands ###
