"""Add the per-finding stage trace.

Records what each identification stage measured and why it decided as it did.
Nullable, and only written for findings that are not a clean pass, so existing
rows stay valid and the column costs nothing for the majority of a run.

Revision ID: 0002
Revises: 0001
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stage_trace_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.drop_column('stage_trace_json')

    # ### end Alembic commands ###
